version: '3'

services:
  api:
    build: .
    command: npm run start:prod
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
